
--playgroup
insert into playgroup values (DEFAULT, 'GayChat', '', '');

--gay
insert into gay values (DEFAULT, '', '', 'Adam', NOW());
insert into gay values (DEFAULT, '', '', 'Artex', NOW());
insert into gay values (DEFAULT, '', '', 'Asyd', NOW());
insert into gay values (DEFAULT, '', '', 'Jakub Král', NOW());
insert into gay values (DEFAULT, '', '', 'Jerry', NOW());
insert into gay values (DEFAULT, '', '', 'Jirka', NOW());
insert into gay values (DEFAULT, '', '', 'Luky', NOW());
insert into gay values (DEFAULT, '', '', 'Malej Kuba', NOW());
insert into gay values (DEFAULT, '', '', 'Martin', NOW());
insert into gay values (DEFAULT, '', '', 'Martin B', NOW());
insert into gay values (DEFAULT, '', '', 'Mike', NOW());
insert into gay values (DEFAULT, '', '', 'Mira', NOW());
insert into gay values (DEFAULT, '', '', 'Ollie', NOW());
insert into gay values (DEFAULT, '', '', 'Otto', NOW());
insert into gay values (DEFAULT, '', '', 'Pepa', NOW());
insert into gay values (DEFAULT, '', '', 'Peter', NOW());
insert into gay values (DEFAULT, '', '', 'Petr Tejnský', NOW());
insert into gay values (DEFAULT, '', '', 'Rene', NOW());
insert into gay values (DEFAULT, '', '', 'Robert', NOW());
insert into gay values (DEFAULT, '', '', 'Terezie', NOW());
insert into gay values (DEFAULT, '', '', 'Vinni', NOW());
insert into gay values (DEFAULT, '', '', 'Vojta', NOW());
insert into gay values (DEFAULT, '', '', 'Zefon', NOW());
insert into gay values (DEFAULT, '', '', 'Radek', NOW());
insert into gay values (DEFAULT, '', '', 'Honza', NOW());

--deck
insert into deck values (DEFAULT, 'Admiral Beckett Brass', '', NULL);
insert into deck values (DEFAULT, 'Alesha', '', NULL);
insert into deck values (DEFAULT, 'Ana-Pauper', '', NULL);
insert into deck values (DEFAULT, 'Arahbo', '', NULL);
insert into deck values (DEFAULT, 'Atraxa', '', NULL);
insert into deck values (DEFAULT, 'Aurelia', '', NULL);
insert into deck values (DEFAULT, 'Ayili', '', NULL);
insert into deck values (DEFAULT, 'Azusa', '', NULL);
insert into deck values (DEFAULT, 'Big Idea', '', NULL);
insert into deck values (DEFAULT, 'Brago', '', NULL);
insert into deck values (DEFAULT, 'Breya-Precon', '', NULL);
insert into deck values (DEFAULT, 'Brion', '', NULL);
insert into deck values (DEFAULT, 'Bruse/Kraum', '', NULL);
insert into deck values (DEFAULT, 'Crosis', '', NULL);
insert into deck values (DEFAULT, 'Daghatar', '', NULL);
insert into deck values (DEFAULT, 'Daretti', '', NULL);
insert into deck values (DEFAULT, 'Edgar', '', NULL);
insert into deck values (DEFAULT, 'Ephara', '', NULL);
insert into deck values (DEFAULT, 'Etali', '', NULL);
insert into deck values (DEFAULT, 'Gahiji', '', NULL);
insert into deck values (DEFAULT, 'Gaybros', '', NULL);
insert into deck values (DEFAULT, 'Geth', '', NULL);
insert into deck values (DEFAULT, 'Gisa and Geralf', '', NULL);
insert into deck values (DEFAULT, 'Gishath', '', NULL);
insert into deck values (DEFAULT, 'Gitrog', '', NULL);
insert into deck values (DEFAULT, 'Glissa', '', NULL);
insert into deck values (DEFAULT, 'Gonti', '', NULL);
insert into deck values (DEFAULT, 'Grenzo', '', NULL);
insert into deck values (DEFAULT, 'Grusilda', '', NULL);
insert into deck values (DEFAULT, 'Hannah', '', NULL);
insert into deck values (DEFAULT, 'Hapatra', '', NULL);
insert into deck values (DEFAULT, 'Child of alara', '', NULL);
insert into deck values (DEFAULT, 'Inalla', '', NULL);
insert into deck values (DEFAULT, 'Jeleva', '', NULL);
insert into deck values (DEFAULT, 'Jhoira', '', NULL);
insert into deck values (DEFAULT, 'Jumblemorph', '', NULL);
insert into deck values (DEFAULT, 'Kambal', '', NULL);
insert into deck values (DEFAULT, 'Karador', '', NULL);
insert into deck values (DEFAULT, 'Karametra', '', NULL);
insert into deck values (DEFAULT, 'Karlov', '', NULL);
insert into deck values (DEFAULT, 'Kess', '', NULL);
insert into deck values (DEFAULT, 'King Macar', '', NULL);
insert into deck values (DEFAULT, 'Kingpin', '', NULL);
insert into deck values (DEFAULT, 'Kitsune', '', NULL);
insert into deck values (DEFAULT, 'Lazav', '', NULL);
insert into deck values (DEFAULT, 'Lovissa', '', NULL);
insert into deck values (DEFAULT, 'Lyzolda', '', NULL);
insert into deck values (DEFAULT, 'Mairsil', '', NULL);
insert into deck values (DEFAULT, 'Marath', '', NULL);
insert into deck values (DEFAULT, 'Marchesa', '', NULL);
insert into deck values (DEFAULT, 'Mathas', '', NULL);
insert into deck values (DEFAULT, 'Memnarch', '', NULL);
insert into deck values (DEFAULT, 'Meren', '', NULL);
insert into deck values (DEFAULT, 'Mimeoplazma', '', NULL);
insert into deck values (DEFAULT, 'Mina and Denn', '', NULL);
insert into deck values (DEFAULT, 'Molimo', '', NULL);
insert into deck values (DEFAULT, 'Narset', '', NULL);
insert into deck values (DEFAULT, 'Nazahn', '', NULL);
insert into deck values (DEFAULT, 'Neheb', '', NULL);
insert into deck values (DEFAULT, 'Nekusar', '', NULL);
insert into deck values (DEFAULT, 'Niv Mizzet', '', NULL);
insert into deck values (DEFAULT, 'Obzedat', '', NULL);
insert into deck values (DEFAULT, 'Ojutai', '', NULL);
insert into deck values (DEFAULT, 'Ol´ Buzzbark', '', NULL);
insert into deck values (DEFAULT, 'Olivia', '', NULL);
insert into deck values (DEFAULT, 'Omnath', '', NULL);
insert into deck values (DEFAULT, 'Phenax', '', NULL);
insert into deck values (DEFAULT, 'Polukranos', '', NULL);
insert into deck values (DEFAULT, 'Progenitus', '', NULL);
insert into deck values (DEFAULT, 'Purphoros', '', NULL);
insert into deck values (DEFAULT, 'Rakdos', '', NULL);
insert into deck values (DEFAULT, 'Ramos', '', NULL);
insert into deck values (DEFAULT, 'Riku', '', NULL);
insert into deck values (DEFAULT, 'Robodeck', '', NULL);
insert into deck values (DEFAULT, 'Roon', '', NULL);
insert into deck values (DEFAULT, 'Rota', '', NULL);
insert into deck values (DEFAULT, 'Safi-O', '', NULL);
insert into deck values (DEFAULT, 'Safi-P', '', NULL);
insert into deck values (DEFAULT, 'Scarab God', '', NULL);
insert into deck values (DEFAULT, 'Scorpy', '', NULL);
insert into deck values (DEFAULT, 'Selenia', '', NULL);
insert into deck values (DEFAULT, 'Selvala', '', NULL);
insert into deck values (DEFAULT, 'Sharuum', '', NULL);
insert into deck values (DEFAULT, 'Shattergang Bros', '', NULL);
insert into deck values (DEFAULT, 'Sidisi', '', NULL);
insert into deck values (DEFAULT, 'Sigarda', '', NULL);
insert into deck values (DEFAULT, 'Sisay', '', NULL);
insert into deck values (DEFAULT, 'Sliver Overlord', '', NULL);
insert into deck values (DEFAULT, 'Smasher/Thrassios', '', NULL);
insert into deck values (DEFAULT, 'Sram', '', NULL);
insert into deck values (DEFAULT, 'Taigam', '', NULL);
insert into deck values (DEFAULT, 'Tana', '', NULL);
insert into deck values (DEFAULT, 'Tasigur', '', NULL);
insert into deck values (DEFAULT, 'Teferi', '', NULL);
insert into deck values (DEFAULT, 'Thada Adel', '', NULL);
insert into deck values (DEFAULT, 'Thelon', '', NULL);
insert into deck values (DEFAULT, 'Tresserhorn', '', NULL);
insert into deck values (DEFAULT, 'Tymna Ravos', '', NULL);
insert into deck values (DEFAULT, 'Tymna/Bruse', '', NULL);
insert into deck values (DEFAULT, 'Tymna/Kraum', '', NULL);
insert into deck values (DEFAULT, 'Ulasht', '', NULL);
insert into deck values (DEFAULT, 'Ulrich', '', NULL);
insert into deck values (DEFAULT, 'Urabrask', '', NULL);
insert into deck values (DEFAULT, 'Uril', '', NULL);
insert into deck values (DEFAULT, 'Vhati', '', NULL);
insert into deck values (DEFAULT, 'Vorel', '', NULL);
insert into deck values (DEFAULT, 'Wanderer', '', NULL);
insert into deck values (DEFAULT, 'X', '', NULL);
insert into deck values (DEFAULT, 'Yasova', '', NULL);
insert into deck values (DEFAULT, 'Yidris', '', NULL);
insert into deck values (DEFAULT, 'Zedruu', '', NULL);
insert into deck values (DEFAULT, 'Zegana', '', NULL);
insert into deck values (DEFAULT, 'Zur', '', NULL);
insert into deck values (DEFAULT, 'Thrinax', '', NULL);
insert into deck values (DEFAULT, 'Neheb the Worthy', '', NULL);
insert into deck values (DEFAULT, 'Jhoira durdle', '', NULL);